### PR TITLE
Edited

### PR DESCRIPTION
**Pull request by Masterolic**

### CODE REVIEW

**Comment by ghost** [comment]
So you want to promote your bot with my bot? Nice try, lamo.

**Comment by Masterolic** [comment]
Nop I just added lyrics and Saavn support to it my bot have more than this update :)

**Comment by ghost** [comment]
> Nop I just added lyrics and Saavn support to it my bot have more than this update :)

You did a good work, and your bot have way more user than mine, Congo.

But I'm not merging this because of "downloaded my @jhondoebot" this. :3 

I have a plan to add lyrics tho, but i don't wanna use arq for this.

Good luck and thanks for mentioning repo in your bot.

**Comment by Masterolic** [comment]
Ha kk dude thanks , welcome :)

And dude I had made that download result to 320 by ffmpeg:)

And dude I just wana to know by buymeacoffee.com can we do online tranfer by what I get in it without a credit or debit card 🥲

**Comment by ghost** [comment]
> And dude I had made that download result to 320 by ffmpeg:)

Yeh, I saw. I didn't added 320 because it needs ffmpeg. (actully I did first time, then removed :p)

> And dude I just wana to know by buymeacoffee.com can we do online tranfer by what I get in it without a credit or debit card smiling_face_with_tear

No Idea, Nobody donated me yet. :(

**Comment by Masterolic** [comment]
Ham thank you 

And how you know my bot 😂😂

**Comment by ghost** [comment]
> Ham thank you
> And how you know my bot 😂 😂 



I checked your repo after your pull. :p

**Comment by Masterolic** [comment]
Ha kk

**Comment by Masterolic** [comment]
And you deploy in heroku itself?

Mine is banned there 🥲😂

**Comment by ghost** [comment]
@Masterolic Yeh, heroku didn't ban me for hosting this. 
Maybe they will. 😂

**Comment by Masterolic** [comment]
Yes I just used your repo without editing no issue but mine they ban in 24hrs 🥲

Do you know any free servers without credit card 🥲🥲

**Comment by ghost** [comment]
@Masterolic They started banning repo that use too much bandwith. :(

**Comment by Masterolic** [comment]
Yes 🥲🤣

**Comment by Masterolic** [comment]
Bro how can I contact you on telegram 🙂 I have some doubts in metadata 🙂 and I found solution for /tmp/thumbnail error 😂😂❤️

**Comment by ghost** [comment]
> Bro how can I contact you on telegram slightly_smiling_face I have some doubts in metadata slightly_smiling_face and I found solution for /tmp/thumbnail error joyjoyheart

Pinged. :3 But your userbot saying that you are busy. 😆

**Comment by Masterolic** [comment]
Ohh kk 😂😅😅 I was playing game 😅😅

**Pull request closed without merging**
